# ZSH config
ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

# Plugins
plugins=(git)

source $ZSH/oh-my-zsh.sh

. $HOME/dotfiles/lib/z/z.sh

# Customize to your needs...
#JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home

# Add home bin folder to path
HOME_BIN=~/bin
export PATH=$PATH:$HOME_BIN

# Add ant directoy
export ANT_HOME=$HOME_BIN/apache-ant-1.9.3

# Add bin directoy
export PATH=$PATH:$ANT_HOME/bin

# Ant tree directoy
export PATH=$PATH:~/bin/tree

# Maven directoy
export M2_HOME=$HOME_BIN/apache-maven-3.1.1
PATH=$M2_HOME/bin:$PATH

# MySQL
export MYSQL_HOME=/usr/local/mysql
export PATH=${PATH}:$MYSQL_HOME/bin

# Latex 
export PATH=${PATH}:/usr/texbin

